
block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('res/app.ico', 'res'),
        ('res/ohwl.dll', 'res'),
    ],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'pythonnet',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'tkinter',
        'unittest',
        'email',
        'html',
        'xml',
        'pydoc',
        'setuptools',
        'pip',
        'wheel',
        'pkg_resources',
        'pygments',
        'sphinx',
        'IPython',
        'jupyter',
        'notebook',
        'sqlalchemy',
        'sqlite3',
        'ssl',
        'socket',
        'http',
        'Pyinstaller',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure,level=9,)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='监控器',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=True,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=r'D:\CodeHub\Python\Monit\res\app.ico',
    uac_admin = False
)